/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Overview */
        get: operations["get_overview_api_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/commodity/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Commodity */
        get: operations["get_commodity_api_commodity__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CommodityMeta */
        CommodityMeta: {
            /** Slug */
            slug: string;
            /** Resource Id */
            resource_id: number;
            /** Name */
            name: string;
            /** Unit */
            unit: string;
            /** Current Flag */
            current_flag: string;
            /** Latest Price */
            latest_price: number;
        };
        /** CommodityOverview */
        CommodityOverview: {
            /** Slug */
            slug: string;
            /** Resource Id */
            resource_id: number;
            /** Name */
            name: string;
            /** Unit */
            unit: string;
            /** Latest Price */
            latest_price: number;
            /** Price Dev Pct */
            price_dev_pct: number;
            /** Flag */
            flag: string;
            /** Days In Flag */
            days_in_flag: number | null;
            /** Flag History */
            flag_history: components["schemas"]["FlagHistoryEntry"][];
        };
        /** CommodityResponse */
        CommodityResponse: {
            meta: components["schemas"]["CommodityMeta"];
            /** Price Trend */
            price_trend: components["schemas"]["PriceTrendEntry"][];
            comparison: components["schemas"]["ComparisonData"];
            inventory: components["schemas"]["InventoryData"] | null;
            /** Production Trend */
            production_trend: components["schemas"]["ProductionTrendEntry"][];
        };
        /** ComparisonData */
        ComparisonData: {
            /** Current Price */
            current_price: number;
            /** Avg 30D */
            avg_30d: number;
            /** Avg 1Y */
            avg_1y: number;
            /** Dev Vs 30D Pct */
            dev_vs_30d_pct: number;
            /** Dev Vs 1Y Pct */
            dev_vs_1y_pct: number;
        };
        /** FlagHistoryEntry */
        FlagHistoryEntry: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Flag */
            flag: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HeadlineData */
        HeadlineData: {
            /** Headline */
            headline: string;
            /** Source */
            source: string;
            /**
             * Published At
             * Format: date-time
             */
            published_at: string;
            /** Resource Name */
            resource_name: string;
            /** Sentiment */
            sentiment: number;
            /** Url */
            url: string | null;
        };
        /** InventoryData */
        InventoryData: {
            /** Current Level */
            current_level: number;
            /** Unit */
            unit: string;
            /** Five Year Max */
            five_year_max: number;
            /** Fill Pct */
            fill_pct: number;
            /** Streak Direction */
            streak_direction: string;
            /** Streak Weeks */
            streak_weeks: number;
            /**
             * Latest Date
             * Format: date
             */
            latest_date: string;
        };
        /** OverviewMeta */
        OverviewMeta: {
            /**
             * Last Updated
             * Format: date
             */
            last_updated: string;
            /** Data Freshness */
            data_freshness: string;
        };
        /** OverviewResponse */
        OverviewResponse: {
            /** Commodities */
            commodities: components["schemas"]["CommodityOverview"][];
            /** Headlines */
            headlines: components["schemas"]["HeadlineData"][];
            supply_balance: components["schemas"]["SupplyBalance"] | null;
            meta: components["schemas"]["OverviewMeta"];
        };
        /** PriceTrendEntry */
        PriceTrendEntry: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Price */
            price: number;
            /** Risky Threshold */
            risky_threshold: number | null;
            /** Critical Threshold */
            critical_threshold: number | null;
        };
        /** ProductionTrendEntry */
        ProductionTrendEntry: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Volume Tbpd */
            volume_tbpd: number;
            /** Rolling Avg 12M */
            rolling_avg_12m: number | null;
        };
        /** SupplyBalance */
        SupplyBalance: {
            /** Current Gap Tbpd */
            current_gap_tbpd: number;
            /** Min Gap Tbpd */
            min_gap_tbpd: number;
            /** Max Gap Tbpd */
            max_gap_tbpd: number;
            /**
             * Latest Date
             * Format: date
             */
            latest_date: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_overview_api_overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewResponse"];
                };
            };
        };
    };
    get_commodity_api_commodity__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommodityResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
